AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI Curated Newsletter - MVP

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Runtime: python3.12
    Architectures:
      - x86_64

Parameters:
  FromEmail:
    Type: String
    Description: Sender email address (must be verified in SES)
    Default: noreply@example.com

  ToEmail:
    Type: String
    Description: Recipient email address
    Default: recipient@example.com

Resources:
  # Lambda Function
  NewsletterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-curated-newsletter
      CodeUri: .
      Handler: src.handler.lambda_handler
      Environment:
        Variables:
          CACHE_TABLE_NAME: !Ref CacheTable
          HISTORY_TABLE_NAME: !Ref HistoryTable
          SOURCES_CONFIG_PATH: config/sources.json
          FROM_EMAIL: !Ref FromEmail
          TO_EMAIL: !Ref ToEmail
          BEDROCK_MODEL_ID: anthropic.claude-3-5-sonnet-20241022-v2:0
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CacheTable
        - DynamoDBCrudPolicy:
            TableName: !Ref HistoryTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-5-sonnet-20241022-v2:0'
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
      Events:
        TuesdaySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 9 ? * TUE *)
            Description: Run newsletter on Tuesday at 09:00 UTC
            Enabled: true
        FridaySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 9 ? * FRI *)
            Description: Run newsletter on Friday at 09:00 UTC
            Enabled: true

  # DynamoDB Cache Table
  CacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ai-curated-newsletter-cache
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      Tags:
        - Key: Application
          Value: ai-curated-newsletter

  # DynamoDB History Table
  HistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ai-curated-newsletter-history
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Application
          Value: ai-curated-newsletter

Outputs:
  NewsletterFunction:
    Description: Newsletter Lambda Function ARN
    Value: !GetAtt NewsletterFunction.Arn

  NewsletterFunctionIamRole:
    Description: Implicit IAM Role created for Newsletter function
    Value: !GetAtt NewsletterFunctionRole.Arn

  CacheTableName:
    Description: DynamoDB Cache Table Name
    Value: !Ref CacheTable

  HistoryTableName:
    Description: DynamoDB History Table Name
    Value: !Ref HistoryTable
